development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: xxxdb_dev
  pool: 5
  timeout: 5000
  username: testuser
  password: testuser

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: xxxdb_test
  pool: 5
  timeout: 5000
  username: testuser
  password: testuser
